if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows" AND NOT FORCE_ELF)
    set(CMAKE_YASM_COMPILE_OBJECT 
        "<CMAKE_YASM_COMPILER> <DEFINES> <INCLUDES> -Xvc -pnasm -rnasm -f win64 -o <OBJECT> --objext=yasm.obj <SOURCE>"
    )
else()
    set(CMAKE_YASM_COMPILE_OBJECT 
        "<CMAKE_YASM_COMPILER> <DEFINES> <INCLUDES> -f elf64 -gdwarf -o <OBJECT> <SOURCE>"
    )
endif()

set(CMAKE_INCLUDE_FLAG_YASM "-I")

set(CMAKE_YASM_INFORMATION_LOADED 1)
