set(CMAKE_SYSTEM_NAME ${CMAKE_HOST_SYSTEM_NAME})
set(CMAKE_SYSTEM_PROCESSOR ${CMAKE_HOST_SYSTEM_PROCESSOR})
set(CMAKE_CONFIGURATION_TYPES Debug Release)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
