set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_CONFIGURATION_TYPES Debug Release)

# Set C compile commands

set(CMAKE_C_COMPILER_WORKS 1)

set(CMAKE_C_COMPILE_OBJECT
    "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> /c /Fo:<OBJECT> <SOURCE>"
)

set(CMAKE_C_LINK_EXECUTABLE
      "<CMAKE_LINKER> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> /OUT:<TARGET> <OBJECTS> <LINK_LIBRARIES>"
)

set(CMAKE_C_CREATE_STATIC_LIBRARY
      "<CMAKE_AR> <FLAGS> <LINK_FLAGS> /NOLOGO /OUT:<TARGET> <OBJECTS>"
)

set(CMAKE_C_FLAGS_INIT)
set(CMAKE_C_LINK_FLAGS_INIT)

# Set filenames
set(CMAKE_STATIC_LIBRARY_PREFIX_C "")
set(CMAKE_STATIC_LIBRARY_SUFFIX_C .lib)
set(CMAKE_C_OUTPUT_EXTENSION .obj)
set(CMAKE_EXECUTABLE_SUFFIX_C "")
